---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'plugin:prettier/recommended'
  - prettier
plugins:
  - node
  - prettier
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-var: error
  prefer-const: error
  comma-dangle:
    - error
    - always-multiline
  no-underscore-dangle:
    - error
overrides:
- files: "**/*.test.js"
  rules:
    node/no-unpublished-require: 0
    node/no-missing-require: 0

env:
  node: true
  es6: true
