# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      # run lint for all files
      - run: |
          mkdir -p lint
          npm run --silent lint-ci
      - store_test_results:
          path: lint
      - store_artifacts:
          path: lint

      # create jest result folder
      - run: mkdir -p jest

      # run service tests
      - run: 
          command: npm test -- --testResultsProcessor jest-junit-reporter --coverageReporters lcov --coverage
          environment:
            TEST_REPORT_PATH: jest
            TEST_REPORT_FILENAME: service-report.xml

      # run fi.xxx.sample tests
      - run:
          pwd: modules/fi.xxx.sample
          command: npm install && npm test -- --testResultsProcessor jest-junit-reporter --coverageReporters lcov --coverage
          environment:
            TEST_REPORT_PATH: ../../jest
            TEST_REPORT_FILENAME: sample-report.xml

      # run fi.xxx.test tests
      - run:
          pwd: modules/fi.xxx.test
          command: npm install && npm test -- --testResultsProcessor jest-junit-reporter --coverageReporters lcov --coverage
          environment:
            TEST_REPORT_PATH: ../../jest
            TEST_REPORT_FILENAME: test-report.xml

      # store all jest results
      - store_test_results:
          path: jest
      - store_artifacts:
          path: jest