# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - service-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - service-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: service-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # run lint
      - run: |
          mkdir -p reports
          npm run lint-ci
      - store_test_results:
          path: /reports
      - store_artifacts:
          path: /reports  