version: 2.1

commands:
  test-nodejs:
    steps:
      - checkout

      - run:
          name: Install Google Cloud SDK packages
          command: |
            sudo apt-get update -y && sudo apt-get install apt-transport-https ca-certificates gnupg -y
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update -y && sudo apt-get install google-cloud-sdk google-cloud-sdk-datastore-emulator google-cloud-sdk-pubsub-emulator -y

      - run:
          name: Prepare tests
          command: |
            bash .circleci/install.sh

      - run:
          name: Run Prettier check for all JS files
          command: ./node_modules/.bin/prettier --check "**/*.js"

      - run:
          name: Run ESLint
          command: |
            npm run lint --silent -- --format junit --output-file reports/eslint.xml

      - run: 
          name: service unit tests
          command: |
            npm test -- --ci && codecov -p . -F service
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports
            JEST_JUNIT_OUTPUT_NAME: service-report.xml

      - run:
          name: fi.xxx.sample unit tests
          working_directory: modules/fi.xxx.sample
          command: npm test -- --ci && codecov -p ../.. -F sample
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../../reports
            JEST_JUNIT_OUTPUT_NAME: sample-report.xml

      - run:
          name: fi.xxx.test unit tests
          working_directory: modules/fi.xxx.test
          command: npm test -- --ci && codecov -p ../.. -F test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../../reports
            JEST_JUNIT_OUTPUT_NAME: test-report.xml

      - run:
          name: fi.xxx.datastore unit tests
          working_directory: modules/fi.xxx.datastore
          command: npm test -- --ci && codecov -p ../.. -F datastore
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../../reports
            JEST_JUNIT_OUTPUT_NAME: datastore-report.xml

      - run:
          name: fi.xxx.pubsub unit tests
          working_directory: modules/fi.xxx.pubsub
          command: npm test -- --ci && codecov -p ../.. -F pubsub
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../../reports
            JEST_JUNIT_OUTPUT_NAME: pubsub-report.xml

      - run:
          name: List code coverage reports
          working_directory: ./reports
          command: |
            ls -la

      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

jobs:
  node-v12:
    docker:
      - image: cimg/node:16.6
    steps:
      - test-nodejs
  node-v14:
    docker:
      - image: cimg/node:16.6
    steps:
      - test-nodejs
  node-v16:
    docker:
      - image: cimg/node:16.6
    steps:
      - test-nodejs

workflows:
  version: 2
  commit:
    jobs:
      - node-v12
      - node-v14
      - node-v16
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - node-v12
      - node-v14
      - node-v16
