# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - service-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - service-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: service-dependencies-{{ checksum "package.json" }}

      # run lint
      - run: |
          mkdir -p lint
          npm run --silent lint-ci
      - store_test_results:
          path: lint
      - store_artifacts:
          path: lint

      # run service tests!
      - run: mkdir -p jest
      - run: 
          command: npm test -- --testResultsProcessor jest-junit-reporter --coverageReporters lcov --coverage
          environment:
            TEST_REPORT_PATH: jest # used by jest-junit-reporter
            TEST_REPORT_FILENAME: service-report.xml # used by jest-junit-reporter
      - store_test_results:
          path: jest
      - store_artifacts:
          path: jest